let age = 20;
let marks = 95.5;
let name = "Jyothsna";
let college = "SVECW";
let isHappy = true;
let isPlaced = false;
console.log("Name:", name);
console.log("College:", college);
console.log("Age:", age);
console.log("Marks:", marks);
console.log("Is Happy?:", isHappy);
export {};